services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - url-shortener
      - url-shortener-backend
      - url-shortener-db
    ports:
      - 80:80
  
  url-shortener:
    container_name: frontend
    build:
      context: ./shortener-frontend
    restart: on-failure
    env_file:
      - .env

  url-shortener-backend:
    container_name: backend
    build:
      context: ./shortener-backend
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres

  url-shortener-db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./shortener-db:/var/lib/psql/data